import { createSlice } from '@reduxjs/toolkit';

// Define your sample data
const sampleData = [
    {
        "asin": "B0D1XD1ZV3",
        "product_title": "Apple AirPods Pro (2nd Generation) Wireless Ear Buds with USB-C Charging, Up to 2X More Active Noise Cancelling Bluetooth Headphones, Transparency Mode, Adaptive Audio, Personalized Spatial Audio",
        "product_price": "$189.99",
        "product_original_price": "$249.00",
        "currency": "USD",
        "product_star_rating": "4.6",
        "product_num_ratings": 1395,
        "product_url": "https://www.amazon.com/dp/B0D1XD1ZV3",
        "product_photo": "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 4,
        "product_minimum_offer_price": "$150.09",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Sat, Jul 20 Or fastest delivery Wed, Jul 17",
        "has_variations": false
    },
    {
        "asin": "B09MVCQJBJ",
        "product_title": "Xbox",
        "product_price": "$0.00",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.3",
        "product_num_ratings": 64,
        "product_url": "https://www.amazon.com/dp/B09MVCQJBJ",
        "product_photo": "https://m.media-amazon.com/images/I/41amEfnVeyL._AC_UL960_FMwebp_QL65_.png",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$0.00",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "Jul 8, 2024",
        "delivery": "Available instantly on compatible devices",
        "has_variations": false
    },
    {
        "asin": "B0D7STYV9Q",
        "product_title": "Melons Sandbox Playgrounds",
        "product_price": "$0.00",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "1",
        "product_num_ratings": 1,
        "product_url": "https://www.amazon.com/dp/B0D7STYV9Q",
        "product_photo": "https://m.media-amazon.com/images/I/71FIQm32XTL._AC_UL960_FMwebp_QL65_.png",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$0.00",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "Jun 22, 2024",
        "delivery": "Available instantly on compatible devices",
        "has_variations": false
    },
    {
        "asin": "B0CS12LZLS",
        "product_title": "NESCAFÉ Gold Espresso Blonde, Instant Coffee, 3.5 oz",
        "product_price": "$6.68",
        "unit_price": "$1.91",
        "unit_count": 3,
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.6",
        "product_num_ratings": 362,
        "product_url": "https://www.amazon.com/dp/B0CS12LZLS",
        "product_photo": "https://m.media-amazon.com/images/I/71tPLfAANDL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$6.68",
        "is_best_seller": true,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "20K+ bought in past month",
        "delivery": "FREE delivery on $35 shipped by Amazon.",
        "has_variations": false
    },
    {
        "asin": "B0CSYG2CP3",
        "product_title": "Car Carplay Cable for iPhone 15 15 Pro Max 15 Plus Cable, USB A to USB C for Carplay USB C Cord, iPad usb C Cable 10th Gen iPad Pro iPad Air 5th 4th Mini 6th Gen Car Charger Cable Cord Replacement 3FT",
        "product_price": "$8.99",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.6",
        "product_num_ratings": 741,
        "product_url": "https://www.amazon.com/dp/B0CSYG2CP3",
        "product_photo": "https://m.media-amazon.com/images/I/61fpyOCUDML._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$8.99",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Sat, Jul 20 on $35 of items shipped by AmazonOr fastest delivery Wed, Jul 17",
        "has_variations": false
    },
    {
        "asin": "0140280197",
        "product_title": "The 48 Laws of Power",
        "product_price": "$14.55",
        "product_original_price": "$26.00",
        "currency": "USD",
        "product_star_rating": "4.7",
        "product_num_ratings": 78038,
        "product_url": "https://www.amazon.com/dp/0140280197",
        "product_photo": "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 63,
        "product_minimum_offer_price": "$7.69",
        "is_best_seller": true,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "List: ",
        "delivery": "FREE delivery Sat, Jul 20 on $35 of items shipped by AmazonOr fastest delivery Wed, Jul 17",
        "has_variations": false
    },
    {
        "asin": "B0D7MC3XH1",
        "product_title": "YOYO School: YOYO Doll School life Dress up",
        "product_price": "$0.00",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.8",
        "product_num_ratings": 6,
        "product_url": "https://www.amazon.com/dp/B0D7MC3XH1",
        "product_photo": "https://m.media-amazon.com/images/I/81m++AruMtL._AC_UL960_FMwebp_QL65_.png",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$0.00",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "Jun 20, 2024",
        "delivery": "Available instantly on compatible devices",
        "has_variations": false
    },
    {
        "asin": "B0D5WSJCH8",
        "product_title": "Toca Games",
        "product_price": "$12.99",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "5",
        "product_num_ratings": 3,
        "product_url": "https://www.amazon.com/dp/B0D5WSJCH8",
        "product_photo": "https://m.media-amazon.com/images/I/81tWRAHme7L._AC_UL960_FMwebp_QL65_.png",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$12.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "Jun 2, 2024",
        "delivery": "Available instantly on compatible devices",
        "has_variations": false
    },
    {
        "asin": "B0D3PBB78P",
        "product_title": "EA SPORTS College Football 25 - PlayStation 5",
        "product_price": "$69.99",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.com/dp/B0D3PBB78P",
        "product_photo": "https://m.media-amazon.com/images/I/81aE0GBL2mL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$69.99",
        "is_best_seller": true,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "Jul 19, 2024",
        "delivery": "FREE deliveryThis item will be released on July 19, 2024.",
        "has_variations": false
    },
    {
        "asin": "1649374186",
        "product_title": "Onyx Storm (Deluxe Limited Edition) (The Empyrean, 3)",
        "product_price": "$19.78",
        "product_original_price": "$32.99",
        "currency": "USD",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.com/dp/1649374186",
        "product_photo": "https://m.media-amazon.com/images/I/9101MLPcFTL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$19.78",
        "is_best_seller": true,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "List: ",
        "delivery": "FREE delivery Mon, Jan 27, 2025 on $35 of items shipped by AmazonOr fastest delivery Tue, Jan 21, 2025 This title will be released on January 21, 2025.",
        "has_variations": false
    }
];

// Create a slice for sample data
const sampleDataSlice = createSlice({
    name: 'sampleData',
    initialState: {
        items: sampleData
    },
    reducers: {
        // Define any reducers you need here
    }
});

export const {} = sampleDataSlice.actions;
export default sampleDataSlice.reducer;
